dataloader: nvidia_dataloader.NvidiaLoader
phase: train
num_epoch: 30
work_dir: ./work_dir/cn_xxl_kdeq_warm/
batch_size: 8
test_batch_size: 8
num_worker: 8
device: 0
log_interval: 50
eval_interval: 1
save_interval: 10
framesize: 32
pts_size: 172
dynamic_pts_size: false
strict_load: false
weights: /notebooks/Manta/experiments/work_dir/pgcnet_quat_head/best_model.pt
optimizer_args:
  scheduler: constant_then_cosine_then_lock
  cosine_start: 9999
  num_epochs: 30
  optimizer: Adam
  base_lr: 0.00001
  step:
  - 9999
  weight_decay: 0.03
  start_epoch: 0
  nesterov: false
  lock_start: 9999
  eta_min_ratio: 0.01
train_loader_args:
  phase: train
  framerate: 32
test_loader_args:
  phase: test
  framerate: 32
model: models.motion_cleanest_kd.MotionCleanestLinXLKD
model_args:
  pts_size: 172
  num_classes: 25
  knn:
  - 32
  - 24
  - 48
  - 24
  topk: 8
  multi_scale_num_scales: 5
  lxl_hidden_dim: 256
  lxl_mlp_dim: 512
  lxl_num_layers: 4
  lxl_bidirectional: true
  lxl_residual_scale: 0.7
  teacher_ckpt: /notebooks/Manta/experiments/work_dir/pgcnet_quat_head/best_model.pt
  P_path: P_eq.npy
  kd_temp: 4.0
  kd_weight: 0.0
  eq_lambda0: 0.5
  eq_decay_end: 60
resume: false
min_best_acc: 88.0
ignore_weights: []
config: cn_xxl_kdeq_warm.yaml
random_seed: 0
