alpha: 0.7
batch_size: 16
config: quat_pointnet_realctrl.yaml
dataloader: nvidia_dataloader.NvidiaLoader
device: 0
dynamic_pts_size: false
eval_interval: 1
framesize: 32
freeze: null
ignore_weights: []
log_interval: 50
min_best_acc: 0.0
model: models.motion_quat_pointnet.MotionQuatPointNet
model_args:
  num_classes: 25
  pts_size: 172
  framesize: 32
  coord_channels: 4
  q_dim: 48
  n_layers: 3
  dropout: 0.3
  head_hidden: 256
  mode: real
  real_width: 144
num_epoch: 120
num_worker: 8
optimizer_args:
  base_lr: 0.0003
  cosine_start: 60
  eta_min_ratio: 0.01
  lock_start: 110
  nesterov: false
  num_epochs: 120
  optimizer: Adam
  scheduler: constant_then_cosine_then_lock
  start_epoch: 0
  step:
  - 60
  - 90
  - 110
  weight_decay: 0.03
phase: train
print_log: true
pts_extra_epochs: null
pts_extra_target: null
pts_freeze_after_ep: null
pts_ramp_epochs: null
pts_ramp_target: null
pts_random_range: null
pts_size: 172
qcc_weight_schedule: null
random_fix: true
random_seed: 0
resume: false
save_interval: 5
spatial_source_prefix: ''
spatial_target_prefix: spatial_branch
temporal_source_prefix: ''
temporal_target_prefix: temporal_branch
temporal_weights: null
spatial_weights: null
temperature: 3.0
test_batch_size: 16
test_loader_args:
  framerate: 32
  phase: test
train_loader_args:
  framerate: 32
  phase: train
use_soft_labels: false
valid_loader_args: {}
weights: null
work_dir: ./work_dir/quat_pointnet_realctrl/
